---
title: "Benchmarking Common Pandas in Python and Data.table in R"
output: html_document
date: "2024-02-27"
---


```{r setup, include = FALSE}
library(data.table)
library(reshape2)
library(atime)
library(ggplot2)
library(reticulate)
use_python("C:/Users/amoak/AppData/Local/Programs/Python/Python312/python.exe")
virtualenv_create("fm-proj")
use_virtualenv("fm-proj", required = F)

```

```{python}
file_path = 'data.csv'
```


# Reading Csv files with Pandas and data.table

```{r,warning=FALSE,message=FALSE}

write.colors <- c(
  "data.table::fwrite" = "#D6604D",
  "pandas::to_csv" = "#BF812D"
)

file_path = 'data.csv'
n.rows <- 100
seconds.limit <- 10

atime.write.vary.cols <- atime::atime(
  N = as.integer(10^seq(2, 10, by = 0.2)),
  setup = {
    set.seed(1)
    input.vec <- rnorm(n.rows * N)
    input.mat <- matrix(input.vec, n.rows, N)
    input.df <- data.frame(input.mat)
    
    pd <- import("pandas")
    #input_df_pd <- pd$DataFrame(input.df)
    input_df_pd <- r_to_py(input.df)
    
    

  },
  seconds.limit = seconds.limit,
  "data.table::fwrite" = {
    data.table::fwrite(input.df, tempfile(), showProgress = FALSE)
  },
  "pandas::to_csv" = {
    #reticulate::py_run_string("import pandas as pd")
   # reticulate::py_run_string("input_df_pd.to_csv(file_path, index=False)")
    input_df_pd$to_csv(file_path, index = FALSE)
  }
)

```



```{r,warning=FALSE,message=FALSE}
refs.write.vary.cols <- atime::references_best(atime.write.vary.cols)
pred.write.vary.cols <- predict(refs.write.vary.cols)

gg.write.dt.pd <- plot(pred.write.vary.cols)+
  theme(text=element_text(size=15))+
  ggtitle(sprintf("Write real numbers to CSV, with pandas in Python and data.table in R, %d x N", n.rows))+
  scale_x_log10("N = number of columns to write")+
  scale_y_log10("Computation time (seconds)
median line, min/max band
over 10 timings")+
  facet_null()+
  scale_fill_manual(values=write.colors)+
  scale_color_manual(values=write.colors)
```




```{r,warning=FALSE,message=FALSE}
#png()
#print(gg.write.dt.pd)
ggsave("gg.write.dt.pd.png", gg.write.dt.pd, width = 10, height = 6, units = "in", dpi = 300)
#dev.off()
```





# read a Csv files with Pandas and data.table
```{python}
file_path = 'data.csv'
```

```{r,warning=FALSE,message=FALSE}
read.colors <- c(
  "data.table::fread" = "#D6604D",
  "pandas::read_csv" = "#BF812D"
)
n.rows <- 100
seconds.limit <- 10
file_path = 'data.csv'

atime.read <- atime::atime(
  N = as.integer(10^seq(2, 15, by = 0.2)),
  setup = {
    set.seed(1)
    input.vec <- rnorm(n.rows*N)
    input.mat <- matrix(input.vec, n.rows, N)
    input.df <- data.frame(input.mat)
    input.csv <- tempfile()
    fwrite(input.df, "data.csv")
    
    pd <- import("pandas")
    input_df_pd <- pd$DataFrame(input.df)
    #input_df_pd.to_csv('input.csv', index=False)
    
    
  },
  seconds.limit = seconds.limit,
  "data.table::fread" = {
    data.table::fread("data.csv", showProgress = FALSE)
    
    
  },
  "pandas::read_csv" = {
    pd <- import("pandas")
    reticulate::py_run_string("import pandas as pd")
    reticulate::py_run_string("pd.read_csv(file_path)")
    #py$input_df_pd
  }
)
```


```{r,warning=FALSE,message=FALSE}
refs.read.vary.cols <- atime::references_best(atime.read)
pred.read.vary.cols <- predict(refs.read.vary.cols)

gg.read.pd <- plot(pred.read.vary.cols)+
  theme(text=element_text(size=15))+
  ggtitle(sprintf("Read real numbers to CSV, with pandas in Python and data.table in R, %d x N", n.rows))+
  scale_x_log10("N = number of columns to write")+
  scale_y_log10("Computation time (seconds)
median line, min/max band
over 10 timings")+
  facet_null()+
  scale_fill_manual(values=read.colors)+
  scale_color_manual(values=read.colors)
```

```{r,warning=FALSE,message=FALSE}
#png()
#print(gg.read.pd)
ggsave("gg.read.pd.png", gg.read.pd, width = 10, height = 6, units = "in", dpi = 300)
#dev.off()

gg.read.pd


```
```{r,warning=FALSE,message=FALSE}

ml.colors <- c(
  "data.table::melt"="#D6604D",
  "pandas::pd.melt" = "#BF812D"
  )
n.folds <- 10
n.rows <- 100
seconds.limit <- 10

ml.reshape.atime <- atime::atime(
  N=as.integer(10^seq(2, 15, by=0.2)),
  setup={
    df <- data.frame(
      id = rep(1:N, each = 2),
      category = rep(c("A", "B"), N),
      value = rnorm(2 * N)
      )
    },
  seconds.limit= seconds.limit,
  
  "data.table::melt" = {
    data.table::melt(data.table(df), id.vars = c("id",  "category"),variable.names="variable", value.name = "value")
  },
  "pandas::pd.melt" = {
    py_df <- reticulate::r_to_py(df)
    pd <- import("pandas")
    pd$melt(py_df, id_vars = c("id", "category"), value_name = "score")
    
  }

  )

```

```{r}

ml.reshape.refs <- atime::references_best(ml.reshape.atime)
ml.reshape.pred <- predict(ml.reshape.refs)
ml.wide2long.pd <- plot(ml.reshape.pred)+
  theme(text=element_text(size=15))+
  ggtitle(sprintf("Reshaping from wide to long panda & data.table over %dreal numbers, N times", n.folds))+
  scale_x_log10("N = number of Mean,SD,Length to compute")+
  scale_y_log10("Computation time (seconds)
median line, min/max band
over 10 timings")+
  facet_null()+
  scale_fill_manual(values=ml.colors)+
  scale_color_manual(values=ml.colors)
```

```{r,warning=FALSE,message=FALSE}
#png()
#print(ml.wide2long.pd)
ggsave("ml.wide2long.pd.png", ml.wide2long.pd, width = 10, height = 6, units = "in", dpi = 300)
#dev.off()

ml.wide2long.pd
```


```{r,warning=FALSE,message=FALSE}

ml.colors <- c(
  "data.table::melt" = "#D6604D",
  "pandas::pivot_table" = "#BF812D"
)

n.folds <- 10
n.rows <- 100
seconds.limit <- 1

ml.long2wide.atime <- atime::atime(
  N=as.integer(10^seq(2, 7, by=0.2)),
  
  setup={
    df <- data.frame(
      id = rep(1:N, each = 2),
      category = rep(c("A", "B"), N),
      value = rnorm(2 * N)
      )
    },
  seconds.limit= seconds.limit,
  "data.table::dcast" = {
    data.table::dcast(data.table(df), id ~ category, value.var = "value")
  },
  "pandas::pivot_table" = {
    py_df <- reticulate::r_to_py(df)
    pd <- import("pandas")
    pd$pivot_table(py_df, values = "value", index = "id", columns = "category")
  }
  )

```



```{r,warning=FALSE,message=FALSE}
ml.long2wide.refs <- atime::references_best(ml.long2wide.atime)
ml.long2wide.pred <- predict(ml.long2wide.refs)
ml.long2wide <- plot(ml.long2wide.pred)+
  theme(text=element_text(size=15))+
  ggtitle(sprintf("Reshaping from long to wide over %dreal numbers, N times", n.folds))+
  scale_x_log10("N = number of Mean,SD,Length to compute")+
  scale_y_log10("Computation time (seconds)
median line, min/max band
over 10 timings")+
  facet_null()+
  scale_fill_manual(values=ml.colors)+
  scale_color_manual(values=ml.colors)

```

```{r}
#print(ml.long2wide)
ggsave("ml.long2wide.png", ml.long2wide, width = 10, height = 6, units = "in", dpi = 300)
#dev.off()

#ml.long2wide
```




